import NavHeader from '@/app/NavHeader'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const bodyClass = `${inter} h-full max-w-fit`

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-gray-100">
      <body className={bodyClass}>
        <NavHeader/>
        <main>
          <div className="mx-auto max-w-fit py-6 sm:px-6 lg:px-8 ">
            <div className="min-h-full mt-16"> 
              {children}
            </div>
          </div>
        </main>
        
      </body>
    </html>
  )
}
