import NavHeader2 from '@/app/NavHeader2'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const bodyClass = `${inter} h-full`

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full bg-gray-100">
      <body className={inter.className}>
        <NavHeader2/>
        <main>
          <div className="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
            <div className="min-h-full"> 
              {children}
            </div>
          </div>
        </main>
        
      </body>
    </html>
  )
}
